name: loading_icon_button
description: Loading button with icon and text in Flutter. It's working on all flutter platforms. It's a simple way to show a loading button.
version: 0.0.6
homepage: https://github.com/mohesu/loading_icon_button.git

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  lints: ^2.1.1

flutter:
