name: loading_icon_button
description: Loading button with icon and text in Flutter. It's working on all flutter platforms. It's a simple way to show a loading button.
version: 0.0.7
homepage: https://github.com/mohesu/loading_icon_button.git

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
